dist: trusty
language: java
jdk: oraclejdk8

install: ci/travis-install.sh
script: ci/travis-script.sh

addons:
  sonarcloud:
    organization: 'xfournet-github'

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

before_cache:
  - rm -rf "$HOME/.m2/repository/io/github/xfournet/jconfig"

